In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
import neuprint
from neuprint import Client
from neuprint import NeuronCriteria as NC, SynapseCriteria as SC
from neuprint import  fetch_adjacencies, fetch_neurons
from neuprint.utils import connection_table_to_matrix, merge_neuron_properties

In [10]:
import bct

In [3]:
TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImtpbmdyaW8zN0BnbWFpbC5jb20iLCJsZXZlbCI6Im5vYXV0aCIsImltYWdlLXVybCI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hL0FHTm15eFpHS3lycDZVeDZPVW9WRXowdEFnQ29UenhkaGpRamp3SVdaNHNaPXM5Ni1jP3N6PTUwP3N6PTUwIiwiZXhwIjoxODYzMTIxNjM3fQ.oTuSwX28PBA4FZTlq5I0gqp4i1_ePeJoMLY5WSh83W8"

c = Client('neuprint.janelia.org', 'hemibrain:v1.2.1', TOKEN)

In [4]:
# DNp01 (giant fiber) to DNp11
body_ids = ["2307027729","5813024015", "1565846637", "1405231475", "1466998977", "5813023322", "1100404581", "1226887763", "1228264951", "512851433", "5813026936", "1281324958"]
DNp_ids = [int(i) for i in body_ids]

In [5]:
# read all_connection_df.csv file
all_connection_df = pd.read_csv("all_connection_df.csv")

In [7]:
def make_matrix(conn_df, group_cols='bodyId', weight_col='weight', sort_by=None, make_square=False):
    if isinstance(group_cols, str):
        group_cols = (f"{group_cols}_pre", f"{group_cols}_post")

    assert len(group_cols) == 2, \
        "Please provide two group_cols (e.g. 'bodyId_pre', 'bodyId_post')"

    assert group_cols[0] in conn_df, \
        f"Column missing: {group_cols[0]}"

    assert group_cols[1] in conn_df, \
        f"Column missing: {group_cols[1]}"

    assert weight_col in conn_df, \
        f"Column missing: {weight_col}"

    col_pre, col_post = group_cols
    dtype = conn_df[weight_col].dtype

    agg_weights_df = conn_df.groupby([col_pre, col_post], sort=False)[weight_col].sum().reset_index()
    matrix = agg_weights_df.pivot(col_pre, col_post, weight_col)
    matrix = matrix.fillna(0).astype(dtype)

    if sort_by:
        if isinstance(sort_by, str):
            sort_by = (f"{sort_by}_pre", f"{sort_by}_post")

        assert len(sort_by) == 2, \
            "Please provide two sort_by column names (e.g. 'type_pre', 'type_post')"

        pre_order = conn_df.sort_values(sort_by[0])[col_pre].unique()
        post_order = conn_df.sort_values(sort_by[1])[col_post].unique()
        matrix = matrix.reindex(index=pre_order, columns=post_order)
    else:
        # No sort: Keep the order as close to the input order as possible.
        pre_order = conn_df[col_pre].unique()
        post_order = conn_df[col_post].unique()
        matrix = matrix.reindex(index=pre_order, columns=post_order)

    if make_square:    
        matrix ,_ = matrix.align(matrix.T)
        matrix = matrix.fillna(0.0).astype(matrix.dtypes) # not sure abt dtypes

        # matrix, _ = matrix.align(matrix.T).fillna(0.0).astype(matrix.dtype)
        matrix = matrix.rename_axis('bodyId_pre', axis=0).rename_axis('bodyId_post', axis=1)
        matrix = matrix.loc[sorted(matrix.index), sorted(matrix.columns)]

    return matrix

In [13]:
# convert to NxN adjacency matrix
adj_mat_df = make_matrix(all_connection_df, 'bodyId', make_square=True)

/var/folders/q5/wpyng01x7nld79qn65091y_r0000gn/T/ipykernel_74262/2387842939.py:21: FutureWarning: In a future version of pandas all arguments of DataFrame.pivot will be keyword-only.
  matrix = agg_weights_df.pivot(col_pre, col_post, weight_col)


In [14]:
adj_mat_df

bodyId_post  326253554   357245785   357249472   357249642   357249801   \
bodyId_pre                                                                
326253554           0.0         1.0         3.0         3.0         0.0   
357245785           0.0         0.0         0.0         1.0         0.0   
357249472           0.0         0.0         0.0         0.0         3.0   
357249642           0.0         1.0         0.0         0.0         1.0   
357249801           0.0         0.0         0.0         0.0         0.0   
...                 ...         ...         ...         ...         ...   
7112615127          0.0         0.0         0.0         0.0         0.0   
7112615302          0.0         0.0         0.0         0.0         0.0   
7112615304          0.0         0.0         0.0         0.0         0.0   
7112622763          0.0         0.0         0.0         0.0         0.0   
7112624834          0.0         0.0         0.0         0.0         0.0   

bodyId_post  357249875   358264919   358593042   362473525   387939094   ...  \
bodyId_pre                                                               ...   
326253554           0.0         0.0         9.0       316.0         0.0  ...   
357245785           0.0         0.0         0.0         1.0         0.0  ...   
357249472           0.0         0.0         0.0         0.0         0.0  ...   
357249642           3.0         0.0         0.0         0.0         0.0  ...   
357249801           1.0         0.0         0.0         1.0         3.0  ...   
...                 ...         ...         ...         ...         ...  ...   
7112615127          0.0         0.0         0.0         0.0         0.0  ...   
7112615302          0.0         0.0         0.0         0.0         0.0  ...   
7112615304          0.0         0.0         0.0         0.0         0.0  ...   
7112622763          0.0         0.0         0.0         0.0         0.0  ...   
7112624834          0.0         0.0         0.0         0.0         0.0  ...   

bodyId_post  6398859685  6398859860  6398859865  6400000151  6400000641  \
bodyId_pre                                                                
326253554           0.0         0.0         0.0         0.0         0.0   
357245785           0.0         0.0         0.0         0.0         0.0   
357249472           0.0         0.0         0.0         0.0         0.0   
357249642           0.0         0.0         0.0         0.0         0.0   
357249801           0.0         0.0         0.0         0.0         0.0   
...                 ...         ...         ...         ...         ...   
7112615127          0.0         0.0         0.0         0.0         0.0   
7112615302          0.0         0.0         0.0         0.0         0.0   
7112615304          0.0         0.0         0.0         0.0         0.0   
7112622763          0.0         0.0         0.0         0.0         0.0   
7112624834          0.0         0.0         0.0         0.0         0.0   

bodyId_post  7112615127  7112615302  7112615304  7112622763  7112624834  
bodyId_pre                                                               
326253554           0.0         0.0         0.0         0.0         0.0  
357245785           0.0         0.0         0.0         0.0         0.0  
357249472           0.0         0.0         0.0         0.0         0.0  
357249642           0.0         0.0         0.0         0.0         0.0  
357249801           0.0         0.0         0.0         0.0         0.0  
...                 ...         ...         ...         ...         ...  
7112615127          0.0         0.0         0.0         0.0         0.0  
7112615302          0.0         0.0         0.0         0.0         0.0  
7112615304          0.0         0.0         0.0         0.0         0.0  
7112622763          0.0         0.0         0.0         0.0         0.0  
7112624834          0.0         0.0         0.0         0.0         0.0  

[5596 rows x 5596 columns]

In [15]:
adj_mat = adj_mat_df.to_numpy()

In [30]:
for i in range(10):
    # run bct's Louvain algorithm
    ci, q = bct.community_louvain(adj_mat)
    # get the number of communities
    n_communities = len(np.unique(ci))
    print('{} clusters detected with a modularity of {:.2f}.'.format(n_communities, q))

20 clusters detected with a modularity of 0.45.
72 clusters detected with a modularity of 0.46.
36 clusters detected with a modularity of 0.45.
26 clusters detected with a modularity of 0.45.
31 clusters detected with a modularity of 0.45.


BCTParamError: Modularity infinite loop style G. Please contact the developer.

In [34]:
from sknetwork.clustering import Louvain, get_modularity
from sknetwork.linalg import normalize
from sknetwork.utils import get_membership

from sknetwork.data import from_edge_list
from scipy import sparse

import networkx as nx

In [35]:
dfFilt = all_connection_df[['bodyId_pre', 'bodyId_post', 'weight']] # sknetwork uses 3rd col as weight

In [36]:
graph = from_edge_list(list(dfFilt.itertuples(index=False)), weighted=True, directed=True) # without directed=True, wrong # of elements

In [37]:
graph.adjacency

<5596x5596 sparse matrix of type '<class 'numpy.int64'>'
	with 389065 stored elements in Compressed Sparse Row format>

In [81]:
graph.names

array([ 326253554,  357245785,  357249472, ..., 7112615304, 7112622763,
       7112624834])

In [49]:
clusterAssignments = []

for _ in range(10):
    louvain = Louvain(shuffle_nodes=True)
    labels = louvain.fit_predict(graph.adjacency) # each node (neuron) is assigned a label
    clusterAssignments.append(labels)

    labels_unique, counts = np.unique(labels, return_counts=True)
    print(labels_unique, counts)

[0 1 2 3 4 5 6 7] [1261 1050 1024  998  767  269  157   70]
[0 1 2 3 4 5 6 7] [1397 1091 1075 1041  478  283  161   70]
[0 1 2 3 4 5 6] [1416 1112 1085 1078  579  252   74]
[0 1 2 3 4 5 6 7 8] [1391 1119 1087  859  653  399   70   12    6]
[0 1 2 3 4 5] [1726 1401 1074 1024  299   72]
[0 1 2 3 4 5 6 7] [1400 1198  981  825  695  270  157   70]
[0 1 2 3 4 5 6] [1348 1088 1082 1054  669  284   71]
[0 1 2 3 4 5 6 7] [1496 1211  907  886  571  248  207   70]
[0 1 2 3 4 5 6 7] [1277 1069 1056  979  718  280  147   70]
[0 1 2 3 4 5] [1738 1236  966  788  459  409]


In [51]:
clusterAssignments = np.array(clusterAssignments)
clusterAssignments

In [85]:
# find cluster 0 across all runs to see which neurons are consistently assigned to cluster 0
cluster0_assignments = []
for i in range(10):
    cluster0_assignments.append(np.where(clusterAssignments[i] == 0)[0])

cluster0_assignments = np.array(cluster0_assignments)

/var/folders/q5/wpyng01x7nld79qn65091y_r0000gn/T/ipykernel_74262/3083997240.py:6: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  cluster0_assignments = np.array(cluster0_assignments)


In [107]:
# use cluster0 ids to find the corresponding neuron bodyIds
cluster0_bodyIds = []
for i in range(10):
    cluster0_bodyIds.append(graph.names[cluster0_assignments[i]])

In [157]:
# identify which neurons are consistently assigned to cluster 0 by comparing each cluster0_bodyIds to the rest
print(set(cluster0_bodyIds[0]).intersection(*cluster0_bodyIds[1:]))
for i in range(1, 9):
    print(set(cluster0_bodyIds[i]).intersection(*cluster0_bodyIds[:i], *cluster0_bodyIds[i+1:]))
print(set(cluster0_bodyIds[9]).intersection(*cluster0_bodyIds[:9]))

set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
